name: "build-publish"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 5284-snapcraft
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: build
    - uses: snapcore/action-publish@v1
      with:
        store_login: ${{ secrets.SNAP_STORE_LOGIN }}
        snap: ${{ steps.build.outputs.snap }}
        release: edge
